Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
processo = Process()

qubits = processo.alloc(2)

# Preparando o estado de Bell
cat(kron(H, I), CNOT)(*qubits)

estado_quÃ¢ntico = dump(qubits)

print("Estado quÃ¢ntico antes da medida")
print_state(qubits)

medida = measure(qubits[0])
print("Resultado da medida do primeiro qubit:", medida.value)

print("Estado quÃ¢ntico apÃ³s o colapso")
print_state(qubits)
------------------

----- stdout -----
Estado quÃ¢ntico antes da medida
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[36], line 11[0m
[1;32m      8[0m estado_quÃ¢ntico [38;5;241m=[39m dump(qubits)
[1;32m     10[0m [38;5;28mprint[39m([38;5;124m"[39m[38;5;124mEstado quÃ¢ntico antes da medida[39m[38;5;124m"[39m)
[0;32m---> 11[0m [43mprint_state[49m(qubits)
[1;32m     13[0m medida [38;5;241m=[39m measure(qubits[[38;5;241m0[39m])
[1;32m     14[0m [38;5;28mprint[39m([38;5;124m"[39m[38;5;124mResultado da medida do primeiro qubit:[39m[38;5;124m"[39m, medida[38;5;241m.[39mvalue)

[0;31mNameError[0m: name 'print_state' is not defined

