Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
def plot_rxx():
    from sympy.physics.quantum.circuitplot import CircuitPlot, CreateOneQubitGate
    from sympy.physics.quantum.gate import CNOT, H
    from IPython.display import display, Latex

    RZ = CreateOneQubitGate("RZ", "R_Z(\\theta)")

    display(Latex(r"\text{Porta QuÃ¢ntica RXX}(\theta)"))
    CircuitPlot(H(1) * H(0) * CNOT(1, 0) * RZ(0) * CNOT(1, 0) * H(0) * H(1), 2)


plot_rxx()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[21], line 12[0m
[1;32m      8[0m     display(Latex([38;5;124mr[39m[38;5;124m"[39m[38;5;124m\[39m[38;5;124mtext[39m[38;5;124m{[39m[38;5;124mPorta QuÃ¢ntica RXX}([39m[38;5;124m\[39m[38;5;124mtheta)[39m[38;5;124m"[39m))
[1;32m      9[0m     CircuitPlot(H([38;5;241m1[39m) [38;5;241m*[39m H([38;5;241m0[39m) [38;5;241m*[39m CNOT([38;5;241m1[39m, [38;5;241m0[39m) [38;5;241m*[39m RZ([38;5;241m0[39m) [38;5;241m*[39m CNOT([38;5;241m1[39m, [38;5;241m0[39m) [38;5;241m*[39m H([38;5;241m0[39m) [38;5;241m*[39m H([38;5;241m1[39m), [38;5;241m2[39m)
[0;32m---> 12[0m [43mplot_rxx[49m[43m([49m[43m)[49m

Cell [0;32mIn[21], line 2[0m, in [0;36mplot_rxx[0;34m()[0m
[1;32m      1[0m [38;5;28;01mdef[39;00m [38;5;21mplot_rxx[39m():
[0;32m----> 2[0m     [38;5;28;01mfrom[39;00m [38;5;21;01msympy[39;00m[38;5;21;01m.[39;00m[38;5;21;01mphysics[39;00m[38;5;21;01m.[39;00m[38;5;21;01mquantum[39;00m[38;5;21;01m.[39;00m[38;5;21;01mcircuitplot[39;00m [38;5;28;01mimport[39;00m CircuitPlot, CreateOneQubitGate
[1;32m      3[0m     [38;5;28;01mfrom[39;00m [38;5;21;01msympy[39;00m[38;5;21;01m.[39;00m[38;5;21;01mphysics[39;00m[38;5;21;01m.[39;00m[38;5;21;01mquantum[39;00m[38;5;21;01m.[39;00m[38;5;21;01mgate[39;00m [38;5;28;01mimport[39;00m CNOT, H
[1;32m      4[0m     [38;5;28;01mfrom[39;00m [38;5;21;01mIPython[39;00m[38;5;21;01m.[39;00m[38;5;21;01mdisplay[39;00m [38;5;28;01mimport[39;00m display, Latex

[0;31mModuleNotFoundError[0m: No module named 'sympy'

